/* eslint-disable max-len */
import { Component } from '@angular/core';
import { ResupplyLocationType, ResupplyPoint, ResupplyType } from 'src/app/models/resupply-point.model';

@Component({
  selector: 'pct-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.less'],
})
export class HomeComponent {
  pctResupplies: ResupplyPoint[] = [
    {
      mileMarker: 2623,
      locations: [
        {
          name: 'Mazama',
          milesFromTrail: 18.7,
          locationType: ResupplyLocationType.village,
          resupplyType: ResupplyType.yellow,
          description: "Mazama is a small village, probably the last stop before the border, or first stop if you're sobo. There is a nice café to eat, and the store next to it has some food to make a full resupply although a bit limited and very expensive. Mazama is a favorite simply because of the Lion's Den, a trail angel hosting place that allowed me to get all the information about the trail conditions and alternate route last year. There are a few beds or a lot of camping spots, there's a full kitchen, shower, laundry, and Mary is an amazing host that even cooked some meals or deserts for everyone a few times a week. You can also get a ride or hitch into Winthrop, which has a grocery store, gear shops, restaurants and a post office.",
          icons: {
            favorite: true,
            camping: true,
            lodging: false,
            restaurants: true,
            grocery: false,
            gearShop: false,
            postOffice: false,
          },
        },
      ],
    },
    {
      mileMarker: 2572.9,
      locations: [
        {
          name: 'Stehekin',
          milesFromTrail: 10.75,
          locationType: ResupplyLocationType.village,
          resupplyType: ResupplyType.red,
          description: '',
          icons: {
            favorite: true,
            camping: true,
            lodging: true,
            restaurants: true,
            grocery: false,
            gearShop: false,
            postOffice: true,
          },
        },
      ],
    },
    {
      mileMarker: 2465.2,
      locations: [
        {
          name: 'Stevens Pass',
          milesFromTrail: 0,
          locationType: ResupplyLocationType.resort,
          resupplyType: ResupplyType.red,
          description: '',
          icons: {
            favorite: false,
            camping: false,
            lodging: false,
            restaurants: false,
            grocery: false,
            gearShop: false,
            postOffice: false,
          },
        },
        {
          name: 'Skykomish',
          milesFromTrail: 15,
          locationType: ResupplyLocationType.village,
          resupplyType: ResupplyType.orange,
          description: '',
          icons: {
            favorite: false,
            camping: false,
            lodging: false,
            restaurants: false,
            grocery: false,
            gearShop: false,
            postOffice: false,
          },
        },
        {
          name: 'Leavenworth',
          milesFromTrail: 35.2,
          locationType: ResupplyLocationType.village,
          resupplyType: ResupplyType.yellow,
          description: '',
          icons: {
            favorite: false,
            camping: false,
            lodging: false,
            restaurants: false,
            grocery: false,
            gearShop: false,
            postOffice: false,
          },
        },
        {
          name: 'Wenatchee',
          milesFromTrail: 57.7,
          locationType: ResupplyLocationType.town,
          resupplyType: ResupplyType.green,
          description: '',
          icons: {
            favorite: false,
            camping: false,
            lodging: false,
            restaurants: false,
            grocery: false,
            gearShop: false,
            postOffice: false,
          },
        },
      ],
    },
    {
      mileMarker: 2394.1,
      locations: [
        {
          name: 'Snoqualmie Pass',
          milesFromTrail: 0.2,
          locationType: ResupplyLocationType.resort,
          resupplyType: ResupplyType.red,
          description: '',
          icons: {
            favorite: false,
            camping: false,
            lodging: false,
            restaurants: false,
            grocery: false,
            gearShop: false,
            postOffice: false,
          },
        },
      ],
    },
    {
      mileMarker: 2295.9,
      locations: [
        {
          name: 'White Pass',
          milesFromTrail: 0.5,
          locationType: ResupplyLocationType.resort,
          resupplyType: ResupplyType.red,
          description: '',
          icons: {
            favorite: false,
            camping: false,
            lodging: false,
            restaurants: false,
            grocery: false,
            gearShop: false,
            postOffice: false,
          },
        },
        {
          name: 'Packwood',
          milesFromTrail: 19.9,
          locationType: ResupplyLocationType.town,
          resupplyType: ResupplyType.yellow,
          description: '',
          icons: {
            favorite: false,
            camping: false,
            lodging: false,
            restaurants: false,
            grocery: false,
            gearShop: false,
            postOffice: false,
          },
        },
      ],
    },
    {
      mileMarker: 2229.9,
      locations: [
        {
          name: 'Trout Lake',
          milesFromTrail: 13,
          locationType: ResupplyLocationType.village,
          resupplyType: ResupplyType.orange,
          description: '',
          icons: {
            favorite: false,
            camping: true,
            lodging: false,
            restaurants: true,
            grocery: true,
            gearShop: false,
            postOffice: true,
          },
        },
      ],
    },
    {
      mileMarker: 2148.2,
      locations: [
        {
          name: 'Cascade Locks',
          milesFromTrail: 0,
          locationType: ResupplyLocationType.town,
          resupplyType: ResupplyType.green,
          description: '',
          icons: {
            favorite: false,
            camping: true,
            lodging: true,
            restaurants: true,
            grocery: true,
            gearShop: true,
            postOffice: true,
          },
        },
        {
          name: 'Portland',
          milesFromTrail: 44,
          locationType: ResupplyLocationType.town,
          resupplyType: ResupplyType.green,
          description: '',
          icons: {
            favorite: false,
            camping: true,
            lodging: true,
            restaurants: true,
            grocery: true,
            gearShop: true,
            postOffice: true,
          },
        },
      ],
    },
    {
      mileMarker: 2097.9,
      locations: [
        {
          name: 'Timberline Lodge',
          milesFromTrail: 0,
          locationType: ResupplyLocationType.resort,
          resupplyType: ResupplyType.red,
          description: '',
          icons: {
            favorite: true,
            camping: true,
            lodging: false,
            restaurants: true,
            grocery: false,
            gearShop: false,
            postOffice: false,
          },
        },
      ],
    },
    {
      mileMarker: 2087.5,
      locations: [
        {
          name: 'Government Camp',
          milesFromTrail: 7.9,
          locationType: ResupplyLocationType.village,
          resupplyType: ResupplyType.yellow,
          description: '',
          icons: {
            favorite: false,
            camping: false,
            lodging: false,
            restaurants: false,
            grocery: true,
            gearShop: false,
            postOffice: true,
          },
        },
      ],
    },
    {
      mileMarker: 2046.6,
      locations: [
        {
          name: 'Olallie Lake Resort',
          milesFromTrail: 0.1,
          locationType: ResupplyLocationType.resort,
          resupplyType: ResupplyType.red,
          description: '',
          icons: {
            favorite: false,
            camping: true,
            lodging: true,
            restaurants: false,
            grocery: false,
            gearShop: false,
            postOffice: false,
          },
        },
      ],
    },
    {
      mileMarker: 1996.1,
      locations: [
        {
          name: 'Big Lake Youth Camp',
          milesFromTrail: 0,
          locationType: ResupplyLocationType.resort,
          resupplyType: ResupplyType.red,
          description: '',
          icons: {
            favorite: true,
            camping: false,
            lodging: false,
            restaurants: true,
            grocery: false,
            gearShop: false,
            postOffice: true,
          },
        },
      ],
    },
    {
      mileMarker: 1983.8,
      locations: [
        {
          // Also at 2000.9
          name: 'Sisters',
          milesFromTrail: 24.4,
          locationType: ResupplyLocationType.town,
          resupplyType: ResupplyType.green,
          description: '',
          icons: {
            favorite: true,
            camping: true,
            lodging: true,
            restaurants: true,
            grocery: true,
            gearShop: true,
            postOffice: true,
          },
        },
        {
          // Also at 2000.9
          name: 'Bend',
          milesFromTrail: 38.1,
          locationType: ResupplyLocationType.town,
          resupplyType: ResupplyType.green,
          description: '',
          icons: {
            favorite: false,
            camping: true,
            lodging: true,
            restaurants: true,
            grocery: true,
            gearShop: true,
            postOffice: true,
          },
        },
      ],
    },
    {
      mileMarker: 1952.6,
      locations: [
        {
          name: 'Elk Lake Resort',
          milesFromTrail: 1,
          locationType: ResupplyLocationType.resort,
          resupplyType: ResupplyType.red,
          description: '',
          icons: {
            favorite: false,
            camping: false,
            lodging: true,
            restaurants: true,
            grocery: false,
            gearShop: false,
            postOffice: false,
          },
        },
      ],
    },
    {
      mileMarker: 1906.6,
      locations: [
        {
          name: 'Shelter Cove Resort',
          milesFromTrail: 1,
          locationType: ResupplyLocationType.resort,
          resupplyType: ResupplyType.red,
          description: '',
          icons: {
            favorite: false,
            camping: false,
            lodging: true,
            restaurants: true,
            grocery: false,
            gearShop: false,
            postOffice: true,
          },
        },
      ],
    },
    {
      mileMarker: 1826,
      locations: [
        {
          name: 'Crater Lake National Park',
          // Need to verify
          milesFromTrail: 1,
          locationType: ResupplyLocationType.village,
          resupplyType: ResupplyType.red,
          description: '',
          icons: {
            favorite: false,
            camping: false,
            lodging: true,
            restaurants: true,
            grocery: false,
            gearShop: false,
            postOffice: true,
          },
        },
      ],
    },
    {
      mileMarker: 1821.7,
      locations: [
        {
          name: 'Mazama Village',
          milesFromTrail: 0.6,
          locationType: ResupplyLocationType.village,
          resupplyType: ResupplyType.orange,
          description: '',
          icons: {
            favorite: false,
            camping: true,
            lodging: false,
            restaurants: true,
            grocery: false,
            gearShop: false,
            // Not Post Office
            postOffice: true,
          },
        },
      ],
    },
    {
      mileMarker: 1773.2,
      locations: [
        {
          name: 'Fish Lake Resort',
          milesFromTrail: 2,
          locationType: ResupplyLocationType.resort,
          resupplyType: ResupplyType.red,
          description: '',
          icons: {
            favorite: false,
            camping: false,
            lodging: true,
            restaurants: true,
            grocery: false,
            gearShop: false,
            postOffice: false,
          },
        },
      ],
    },
    {
      mileMarker: 1742.7,
      locations: [
        {
          name: 'Hyatt Lake Resort',
          milesFromTrail: 1.5,
          locationType: ResupplyLocationType.resort,
          resupplyType: ResupplyType.red,
          description: '',
          icons: {
            favorite: false,
            camping: false,
            lodging: true,
            restaurants: true,
            grocery: false,
            gearShop: false,
            postOffice: false,
          },
        },
      ],
    },
    {
      mileMarker: 1718,
      locations: [
        {
          name: 'Callahan\'s Lodge',
          milesFromTrail: 0.25,
          locationType: ResupplyLocationType.resort,
          resupplyType: ResupplyType.red,
          description: '',
          icons: {
            // Need more info
            favorite: false,
            camping: true,
            lodging: true,
            restaurants: true,
            grocery: false,
            gearShop: false,
            postOffice: true,
          },
        },
        {
          name: 'Ashland',
          milesFromTrail: 11,
          locationType: ResupplyLocationType.town,
          resupplyType: ResupplyType.green,
          description: '',
          icons: {
            favorite: true,
            camping: true,
            lodging: true,
            restaurants: true,
            grocery: true,
            gearShop: true,
            postOffice: true,
          },
        },
      ],
    },
    // {
    //   mileMarker: 0,
    //   locations: [
    //     {
    //       name: '',
    //       milesFromTrail: 0,
    //       locationType: ResupplyLocationType.village,
    //       resupplyType: ResupplyType.orange,
    //       description: '',
    //       icons: {
    //         favorite: false,
    //         camping: true,
    //         lodging: false,
    //         restaurants: true,
    //         grocery: false,
    //         gearShop: false,
    //         postOffice: true,
    //       },
    //     },
    //   ],
    // },
    // {
    //   mileMarker: 0,
    //   locations: [
    //     {
    //       name: '',
    //       milesFromTrail: 0,
    //       locationType: ResupplyLocationType.village,
    //       resupplyType: ResupplyType.orange,
    //       description: '',
    //       icons: {
    //         favorite: false,
    //         camping: true,
    //         lodging: false,
    //         restaurants: true,
    //         grocery: false,
    //         gearShop: false,
    //         postOffice: true,
    //       },
    //     },
    //   ],
    // },
    // {
    //   mileMarker: 0,
    //   locations: [
    //     {
    //       name: '',
    //       milesFromTrail: 0,
    //       locationType: ResupplyLocationType.village,
    //       resupplyType: ResupplyType.orange,
    //       description: '',
    //       icons: {
    //         favorite: false,
    //         camping: true,
    //         lodging: false,
    //         restaurants: true,
    //         grocery: false,
    //         gearShop: false,
    //         postOffice: true,
    //       },
    //     },
    //   ],
    // },
  ];
}
